package music_specification_language.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Clip = 0;
  public static final int Instrument = 1;
  public static final int MSLProgram = 2;
  public static final int Segment = 3;
  public static final int segment_clip = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf9e4b29d3c894af7L, 0x8f5f5c06b22ba00bL);
    builder.put(0x552bfe4802320ccfL, Clip);
    builder.put(0x552bfe4802320cccL, Instrument);
    builder.put(0x552bfe4802320cbeL, MSLProgram);
    builder.put(0x552bfe4802320ce5L, Segment);
    builder.put(0x552bfe4802320cecL, segment_clip);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
